name: flutter_aura_2026
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0 

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  uuid: ^4.5.1
  pdf: ^3.12.0
  printing: ^5.14.3
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true